#!/usr/bin/env bash
set -e

# Update package repositories
sudo apt-get update

# Install Nginx
sudo apt-get -y install nginx

# Configure firewall to allow HTTP traffic
sudo ufw allow 'Nginx HTTP'

# Create directories and set permissions
sudo mkdir -p /var/www/html
sudo chmod -R 755 /var/www /var/www/html

# Create index page
echo 'Hello World!' | sudo tee /var/www/html/index.html

# Create a custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html

# Get the server hostname
SERVER=$(hostname)

# Configure Nginx
SERVER_CONFIG="
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;
    location / {
        add_header X-Served-By '$SERVER';
        try_files \$uri \$uri/ =404;
    }
}"

# Write Nginx server configuration to default file
echo "$SERVER_CONFIG" | sudo tee /etc/nginx/sites-enabled/default

# Restart Nginx service to apply changes
sudo systemctl restart nginx
