#!/usr/bin/env bash
# Installs and sets up HAProxy

# Update package repositories
sudo apt-get update

# Install prerequisites
sudo apt-get install -y software-properties-common

# Add HAProxy PPA
sudo add-apt-repository -y ppa:vbernat/haproxy-2.7

# Update package repositories again
sudo apt-get update

# Install HAProxy 2.7
sudo apt-get install -y haproxy=2.7.*

# Enable HAProxy service
echo "ENABLED=1" | sudo tee /etc/default/haproxy > /dev/null

# Configure HAProxy
sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null <<EOF
listen load_balancer
    bind *:80
    mode http
    balance roundrobin
    option httpclose
    option http-server-close
    server web-01 [STUDENT_ID]-web-01:80 check
    server web-02 [STUDENT_ID]-web-02:80 check
EOF

# Start HAProxy service
sudo systemctl start haproxy
