#!/bin/bash

useradd -r -M nginx
service nginx stop
chown -R nginx:nginx /var/log/nginx /var/lib/nginx
sed -i 's/user www-data;/user nginx;/g' /etc/nginx/nginx.conf
sed -i 's/listen 80 default_server;/listen 8080 default_server;/g' /etc/nginx/sites-available/default
service nginx start

